#!/usr/bin/env python3
"""Keep the AUR packages in packaging/aur up to date, and publish them.

After a release is tagged and published on GitHub:

    scripts/update-aur.py release v0.1.0 --dry-run   # show what would change
    scripts/update-aur.py release v0.1.0             # set pkgver, pkgrel, hash, .SRCINFO

That downloads the tag's source archive from GitHub, checks it holds the
version the tag names, and writes its SHA-256 into packaging/aur/plugg/PKGBUILD.
--sha256 takes the hash instead, and --archive hashes a local copy.

    scripts/update-aur.py srcinfo [--check]          # regenerate or check every .SRCINFO

.SRCINFO is always generated by makepkg --printsrcinfo: the host's makepkg if
there is one, otherwise (or with --container) makepkg in an Arch Linux
container pinned by digest, with no network and no host mounts.

Nothing above changes anything outside packaging/aur. Publishing is a separate,
explicit step, run by hand after the change is reviewed and committed:

    scripts/update-aur.py publish plugg --dry-run    # prepare the AUR commit, show it
    scripts/update-aur.py publish plugg              # the same, then git push to the AUR

It clones ssh://aur@aur.archlinux.org/<package>.git into a new temporary
directory, copies PKGBUILD and .SRCINFO into it, commits and pushes.
"""
import argparse
import difflib
import hashlib
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
import urllib.request

REPO = Path(__file__).resolve().parents[1]
AUR = REPO / 'packaging/aur'
PACKAGES = ('plugg', 'plugg-git')
# The Arch Linux image .SRCINFO is generated in when the host has no makepkg.
# packaging/test-aur.py builds the packages in the same image.
ARCH_IMAGE = 'archlinux@sha256:63c7b061c0c001cb7ce4f8d11b63d351c23e7f97121bc5c8bd5d9f431e615d7d'
LABEL = 'plugg.aur=srcinfo'
# The release PKGBUILD's first checksum until the first release sets it. makepkg
# rejects it, so an unset package fails its checksum rather than skipping it.
PLACEHOLDER = '0' * 64
ARCHIVE = '{url}/archive/refs/tags/v{version}.tar.gz'
AUR_REMOTE = 'ssh://aur@aur.archlinux.org/{package}.git'
# Characters pacman allows in a pkgver; a Python version such as 0.1.0 or
# 0.2.0rc1 fits, and a hyphen, which pacman reserves for pkgrel, does not.
PKGVER = re.compile(r'[0-9][0-9A-Za-z.+_]*')
SHA256 = re.compile(r'[0-9a-f]{64}')


def version_from_tag(tag):
    """The pkgver a release tag stands for: v0.1.0 is 0.1.0."""
    match = re.fullmatch(r'v(.+)', tag)
    if not match or not PKGVER.fullmatch(match.group(1)):
        raise ValueError(f'{tag!r} is not a release tag of the form v<version>')
    return match.group(1)


def read_field(text, name):
    """The value of a top-level `name=value` assignment, without quotes."""
    values = re.findall(rf'^{re.escape(name)}=(.*)$', text, re.MULTILINE)
    if len(values) != 1:
        raise ValueError(f'PKGBUILD must assign {name} exactly once')
    return values[0].strip().strip('\'"')


def set_field(text, name, value):
    read_field(text, name)
    return re.sub(rf'^{re.escape(name)}=.*$', lambda _: f'{name}={value}', text, flags=re.MULTILINE)


CHECKSUMS = re.compile(r"^(sha256sums=\(\s*')([^']*)(')", re.MULTILINE)


def first_checksum(text):
    matches = CHECKSUMS.findall(text)
    if len(matches) != 1:
        raise ValueError('PKGBUILD must have one sha256sums array starting with a quoted checksum')
    return matches[0][1]


def set_first_checksum(text, sha256):
    if not SHA256.fullmatch(sha256):
        raise ValueError(f'{sha256!r} is not a lowercase hexadecimal SHA-256')
    first_checksum(text)
    return CHECKSUMS.sub(lambda m: m.group(1) + sha256 + m.group(3), text)


def rewrite(text, version, sha256, pkgrel=None):
    """The release PKGBUILD for `version`, with the source archive's hash.

    A new version starts again at pkgrel 1; the same version keeps its pkgrel
    unless one is given (a packaging-only change raises it by hand)."""
    if not PKGVER.fullmatch(version):
        raise ValueError(f'{version!r} is not a valid pkgver')
    if pkgrel is None:
        pkgrel = read_field(text, 'pkgrel') if read_field(text, 'pkgver') == version else '1'
    if not re.fullmatch(r'[1-9][0-9]*(\.[1-9][0-9]*)?', str(pkgrel)):
        raise ValueError(f'{pkgrel!r} is not a valid pkgrel')
    text = set_field(text, 'pkgver', version)
    text = set_field(text, 'pkgrel', str(pkgrel))
    return set_first_checksum(text, sha256)


def archive_url(text, version):
    return ARCHIVE.format(url=read_field(text, 'url'), version=version)


def sha256_file(path):
    digest = hashlib.sha256()
    with open(path, 'rb') as stream:
        for block in iter(lambda: stream.read(1 << 20), b''):
            digest.update(block)
    return digest.hexdigest()


def check_archive(path, version):
    """Refuse an archive that is not Plugg at `version` in the layout the
    PKGBUILD expects: everything under plugg-<version>/, and that version in
    plugg/__init__.py."""
    top = f'plugg-{version}'
    with tarfile.open(path) as archive:
        names = archive.getnames()
        if not names or any(name != top and not name.startswith(top + '/') for name in names):
            raise ValueError(f'{path} does not hold everything under {top}/')
        if f'{top}/plugg/__init__.py' not in names:
            raise ValueError(f'{path} has no {top}/plugg/__init__.py')
        member = archive.extractfile(f'{top}/plugg/__init__.py')
        declared = re.search(r'^__version__ = "(.*)"$', member.read().decode(), re.MULTILINE)
    if not declared or declared.group(1) != version:
        raise ValueError(f'{path} declares version {declared and declared.group(1)!r}, not {version!r}')


def download(url, target):
    with urllib.request.urlopen(url, timeout=60) as response, open(target, 'wb') as stream:
        shutil.copyfileobj(response, stream)


def srcinfo(pkgbuild_text, container=False):
    """makepkg --printsrcinfo for a PKGBUILD, run on a private copy of it."""
    if not container and shutil.which('makepkg'):
        with tempfile.TemporaryDirectory(prefix='plugg-srcinfo-') as temp:
            (Path(temp) / 'PKGBUILD').write_text(pkgbuild_text)
            # PLUGG_SOURCE is plugg-git's local-build override; the AUR copy
            # must describe the default source.
            env = {key: value for key, value in os.environ.items() if key != 'PLUGG_SOURCE'}
            return subprocess.run(['makepkg', '--printsrcinfo'], cwd=temp, env=env, check=True,
                                  capture_output=True, text=True).stdout
    # makepkg refuses to run as root, so the container runs it as nobody.
    return subprocess.run(
        ['docker', 'run', '--rm', '-i', '--network', 'none', '--user', '65534:65534', '--label', LABEL,
         ARCH_IMAGE, 'sh', '-ec', 'cd "$(mktemp -d)"; cat > PKGBUILD; makepkg --printsrcinfo'],
        input=pkgbuild_text, check=True, capture_output=True, text=True).stdout


def diff(name, old, new):
    return ''.join(difflib.unified_diff(old.splitlines(True), new.splitlines(True),
                                        'a/' + name, 'b/' + name))


def files(package):
    directory = AUR / package
    pkgbuild = (directory / 'PKGBUILD').read_text()
    info = directory / '.SRCINFO'
    return directory, pkgbuild, info.read_text() if info.exists() else ''


def release(args):
    version = version_from_tag(args.tag)
    directory, text, old_info = files('plugg')
    if args.sha256:
        sha256 = args.sha256.lower()
    else:
        with tempfile.TemporaryDirectory(prefix='plugg-aur-') as temp:
            archive = args.archive
            if archive is None:
                url = archive_url(text, version)
                print('Downloading', url, file=sys.stderr)
                archive = Path(temp) / f'plugg-{version}.tar.gz'
                download(url, archive)
            check_archive(archive, version)
            sha256 = sha256_file(archive)
    new_text = rewrite(text, version, sha256, args.pkgrel)
    new_info = srcinfo(new_text, args.container)
    changes = diff('packaging/aur/plugg/PKGBUILD', text, new_text) + \
        diff('packaging/aur/plugg/.SRCINFO', old_info, new_info)
    print(changes or 'packaging/aur/plugg is already up to date.', end='' if changes else '\n')
    if args.dry_run or not changes:
        return 0
    (directory / 'PKGBUILD').write_text(new_text)
    (directory / '.SRCINFO').write_text(new_info)
    print(f'\nUpdated packaging/aur/plugg to {version}. Review and commit it, then publish with\n'
          f'  scripts/update-aur.py publish plugg', file=sys.stderr)
    return 0


def regenerate(args):
    drift = False
    for package in PACKAGES:
        directory, text, old_info = files(package)
        new_info = srcinfo(text, args.container)
        change = diff(f'packaging/aur/{package}/.SRCINFO', old_info, new_info)
        if not change:
            continue
        drift = True
        print(change, end='')
        if not args.check:
            (directory / '.SRCINFO').write_text(new_info)
    if args.check and drift:
        print('A .SRCINFO is out of date; run scripts/update-aur.py srcinfo.', file=sys.stderr)
        return 1
    return 0


def publishable(package, text, info, generated, status):
    """Why a package must not be published as it stands, or None."""
    if generated != info:
        return f'packaging/aur/{package}/.SRCINFO does not match its PKGBUILD; run scripts/update-aur.py srcinfo.'
    if status.strip():
        return f'packaging/aur/{package} has uncommitted changes; commit them first.'
    if package == 'plugg' and first_checksum(text) == PLACEHOLDER:
        return 'The release PKGBUILD has no source hash yet; run scripts/update-aur.py release <tag> first.'
    return None


def git(*args, cwd, capture=False):
    return subprocess.run(['git', *args], cwd=cwd, check=True, text=True,
                          capture_output=capture).stdout


def publish(args):
    package = args.package
    directory, text, info = files(package)
    status = git('status', '--porcelain', '--', str(directory), cwd=REPO, capture=True)
    problem = publishable(package, text, info, srcinfo(text, args.container), status)
    if problem:
        print(problem, file=sys.stderr)
        return 1
    source = git('rev-parse', 'HEAD', cwd=REPO, capture=True).strip()
    with tempfile.TemporaryDirectory(prefix=f'aur-{package}-') as temp:
        clone = Path(temp) / package
        git('clone', '--quiet', AUR_REMOTE.format(package=package), str(clone), cwd=temp)
        extra = sorted(p.name for p in clone.iterdir() if p.name not in ('.git', 'PKGBUILD', '.SRCINFO'))
        if extra:
            print('Note: the AUR repository also holds', ', '.join(extra), file=sys.stderr)
        for name in ('PKGBUILD', '.SRCINFO'):
            shutil.copyfile(directory / name, clone / name)
        git('add', 'PKGBUILD', '.SRCINFO', cwd=clone)
        if subprocess.run(['git', 'diff', '--cached', '--quiet'], cwd=clone).returncode == 0:
            print(f'The AUR already has this {package}; nothing to publish.')
            return 0
        version = f"{read_field(text, 'pkgver')}-{read_field(text, 'pkgrel')}"
        git('commit', '--quiet', '-m', f'Update to {version}\n\nFrom oikoaudio/plugg {source}.', cwd=clone)
        git('--no-pager', 'show', '--stat', '--patch', 'HEAD', cwd=clone)
        if args.dry_run:
            print(f'\nDry run: nothing was pushed to {AUR_REMOTE.format(package=package)}.')
            return 0
        git('push', '--quiet', 'origin', 'HEAD:master', cwd=clone)
        print(f'\nPublished {package} {version} to the AUR.')
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    commands = parser.add_subparsers(dest='command', required=True)
    command = commands.add_parser('release', help='point the plugg package at a release tag')
    command.add_argument('tag', help='the release tag, such as v0.1.0')
    source = command.add_mutually_exclusive_group()
    source.add_argument('--sha256', help="the tag archive's SHA-256, instead of downloading it")
    source.add_argument('--archive', type=Path, help='a local copy of the tag archive to hash')
    command.add_argument('--pkgrel', help='the package release (default: 1 for a new version, else unchanged)')
    command.add_argument('--dry-run', action='store_true', help='show the changes and write nothing')
    command = commands.add_parser('srcinfo', help='regenerate every .SRCINFO from its PKGBUILD')
    command.add_argument('--check', action='store_true', help='report out-of-date files and write nothing')
    command = commands.add_parser('publish', help='commit a package to its AUR repository and push it')
    command.add_argument('package', choices=PACKAGES)
    command.add_argument('--dry-run', action='store_true', help='prepare and show the AUR commit, do not push')
    for command in commands.choices.values():
        command.add_argument('--container', action='store_true',
                             help='generate .SRCINFO in the pinned Arch Linux container even if makepkg is here')
    args = parser.parse_args(argv)
    try:
        return {'release': release, 'srcinfo': regenerate, 'publish': publish}[args.command](args)
    except ValueError as error:
        print(error, file=sys.stderr)
        return 2


if __name__ == '__main__':
    sys.exit(main())
